# Generated by Django 3.1 on 2020-09-12 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('profile', models.TextField()),
                ('skill_1', models.CharField(max_length=100)),
                ('skill_2', models.CharField(max_length=100)),
                ('skill_3', models.CharField(max_length=100)),
                ('Technicale', models.TextField()),
                ('education', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
